### ISSUE TITLE
Error setting time

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_PCF8523#1]
I tried accessing the PCF8523 on an Adalogger Featherwing following the example but get this error when setting the time.

```

>>> import busio
>>> import adafruit_pcf8523
>>> import time
>>> from board import *
>>> myI2C = busio.I2C(SCL, SDA)
>>> rtc = adafruit_pcf8523.PCF8523(myI2C)
>>> rtc.datetime = time.struct_time((2017,1,9,15,6,0,0,9,-1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libraries/drivers/pcf8523/adafruit_pcf8523.py", line 121, in datetime
  File "libraries/helpers/register/adafruit_register/i2c_bcd_datetime.py", line 81, in __set__
AttributeError: 'struct_time' object has no attribute 'second'
```

**Comment by tannewt** [comment]
Do you have the latest PCF8523 library? I believe we just changed it and
you may be looking at a newer example.
~Scott

**Comment by jerryneedell** [comment]
I built the latest bundle - has it bee updated to use the latest version?

**Comment by jerryneedell** [comment]
the library is 5 months old

**Comment by jerryneedell** [comment]
never mind - rebuild bundle - likes like register was updated. - works now
